### PR TITLE
feat: update notifier

### PR DESCRIPTION
**Pull request by vltansky**
Hey, this PR adds update notifications when a new version for `ni` available using [update-notifier](https://github.com/yeoman/update-notifier#readme) (added as a dependency)

you can test it by changing `package.json` version (e.g to `0.4.0`)
output:
```
$ node ./bin/nr lint

> @antfu/ni@0.4.0 lint D:\projects\ni
> eslint "**/*.ts"


   ╭──────────────────────────────────────╮
   │                                      │
   │   Update available 0.4.0 → 0.7.0     │
   │   Run npm i -g @antfu/ni to update   │
   │                                      │
   ╰──────────────────────────────────────╯
```

### CODE REVIEW

**Comment by hannoeru** [comment]
@vltansky can you put `update-notifier` to `devDependencies`? because rollup can bundle it to a single file without any dependencies, and that is why all dependencies are in `devDependencies`.

**Comment by vltansky** [comment]
@hannoeru fixed, thanks.

**Comment by antfu** [comment]
Hi @vltansky thanks a lot for the contribution. But sorry I don't actually like CI tools prints updating messages randomly. ni is essentially a command aliasing tools and there shouldn't be much fixes that needs "update now". Thanks again, and hope my explanations make sense to you.

**Comment by vltansky** [comment]
@antfu PR was inspired by [ncu](https://github.com/raineorshine/npm-check-updates), but I actually agree with your point of view. Thanks for the feedback :)

**Comment by dhruwlalan** [comment]
> Hi @vltansky thanks a lot for the contribution. But sorry I don't actually like CI tools printing updating messages randomly. ni is essentially a command aliasing tools and there shouldn't be much fixes that needs "update now". Thanks again, and hope my explanations make sense to you.

When using it in CI, you might be always installing the latest version of the package when setting up the workflow, right? so there can never be a chance of getting that update message?
just asking for curiosity :)

**Comment by vltansky** [comment]
@antfu probably meant CLI, at least that's how I read it.
If you're talking about CI there are ways to prevent printing messages in CI environments.

**Comment by dhruwlalan** [comment]
Ohh 👍

**Pull request closed without merging**
