### PR TITLE
feat(detect): can choose when there are multiple lock files

### PR DESCRIPTION
**Pull request by classmatewu**
If the project is mixed with multi package management tools, multiple lock files will appear. At present, the default mode is "pnpm > yarn > npm", but I think a more reasonable way is to let users choose according to the lock file.

### CODE REVIEW

**Comment by antfu** [comment]
If you have multiple locks in different dirs, ni will pick the most closed one, which is the same behavior as npm. I don't feel you should have multiple in the same dir. If you really need that case I think you could just use `npm` / `yarn` / `pnpm` directly.

**Comment by classmatewu** [comment]
The existence of multiple lock files may be caused by the mixed use of package management tools by different members of the team. In this case, would it be better for new users to choose?

**Comment by classmatewu** [comment]
ni will pick the most closed one

----- 

How to judge the most closed one

**Comment by antfu** [comment]
CWD and then find up

> mixed use of package management tools by different members of the team

I guess that's the thing you want to avoid in your team?

**Comment by classmatewu** [comment]
thanks a lot

**Comment by classmatewu** [comment]
thanks, yeah

**Pull request closed without merging**
