### PR TITLE
feat: add error message for unsupported commands/package managers

### PR DESCRIPTION
**Pull request by Zeko369**
- [x] Add vscode settings for default formatter / final newline (to match eslint)
- [x] Show an error message if the current pkg manager doesn't support a command

### CODE REVIEW

**Comment by antfu** [comment]
Can you explain why this is needed? Also please revert 1, we are using eslint to format

**Comment by Zeko369** [comment]
Currently if you select a command that's not supported by the package manager (`upgrade` in `bun` or `upgrade-interactive` in `bun`/`npm`, or a lot more stuff in deno #130) it just returns an error code without saying why

Example of `main` vs `this branch`

CleanShot 2023-01-20 at 14 22 16@2x

Regarding the config, a lot of people (me included) have vscode format on save by default, which causes all projects including this one to be formatted by prettier, which isn't something everyone likes (I've read your blogpost and mostly agree for the short line length but still it helps with formatting stuff), vscodes default formatter mostly fixes indents / newlines and matches the projects eslint config, so using it on save doesn't collide with eslint.

Also by default my vscode wasn't inserting new lines so why not set "project styleguides" for everyone using vscode? (since vscode with a prettier extension will format this project wrong and cause people to need to chakge the config, so why not make it work out of the box?)

**Comment by antfu** [comment]
I see. I am good with the error change.

About the config, it's not about opinions, you don't need to convince me as:
- When working on someone else's project, contributors should respect the existing formats (e.g. they should disable the Prettier extension when working on non-prettier projects, vice versa)
- It may be discussable via an issue first, but not directly in a feature PR.
- PR should be single-purpose as possible.

**Comment by Zeko369** [comment]
> PR should be single-purpose as possible.
Agree 😅

> It may be discussable via an issue first, but not directly in a feature PR.
Will open one later

> When working on someone else's project, contributors should respect the existing formats (e.g. they should disable the Prettier extension when working on non-prettier projects, vice versa)
True, how about in this PR I revert config changes and gitignore `.vscode/settings.json`?

**Comment by Zeko369** [comment]
Hey @antfu just wanted to check in if you could review this since I want to finish the other 2 PRs and they're based on this one

**Pull request merged**
