### PR TITLE
feat: ask me when there is no manager

### PR DESCRIPTION
**Pull request by AqingCyan**
### Description

When the manager is not found in the folder, `ni` should ask me something like "There is not project detected in this directory. Do you want to start a new one?" and then proceed to ask me which package manager I want to use.

### Linked Issues

support issue: #122

### Additional context

nothing.

### CODE REVIEW

**Comment by AqingCyan** [comment]
I found that some of the managers had errors when performing dependency installations on empty folders.
I'll try to initialize it later before install.

**Comment by antfu** [comment]
I don't understand the context. It's already doing so to me:
image

**Comment by AqingCyan** [comment]
> I don't understand the context. It's already doing so to me: image

The reason for doing this is to see an [issue](https://github.com/antfu/ni/issues/122): Ask one question to confirm, Instead of creating the project directly.

One more step can make people feel better？

**Comment by antfu** [comment]
I honestly don't think it's necessary. If we real need that, I would just update the message and say `No project detected, choose the agent:`

Closing for now.

**Comment by AqingCyan** [comment]
> I honestly don't think it's necessary. If we real need that, I would just update the message and say `No project detected, choose the agent:`
> 
> Closing for now.

I got it～ thank you

**Pull request closed without merging**
